spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thondsmac/pcs-resources-config.git
      label: master
          
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}

server:
  port: 8888

