spring:
  cloud:
    config:
      server:
        git:
          clone-on-start: 'true'
          uri: http://172.168.3.10:8081/subuu/configuration-data.git
          username: smac-subuu
          password: Smac@123
          
  security:
    user:
      password: Smac@123

server:
  port: 8888



          
