hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  add-proxy-headers: true
  ignoredHeaders: Origin
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    keycloak-service:
        path: /auth/**
        url: http://192.168.10.9:8899
        stripPrefix: false
        sensitiveHeaders:
        
    user-service:
        path: /user-service/**
        url: http://192.168.10.9:8503
        stripPrefix: false
        sensitiveHeaders:
        
    dms-service:
        path: /dms-service/**
        url: http://192.168.10.9:8506
        stripPrefix: false
        sensitiveHeaders:
        
    dms-service-v2:
        path: /dmsone-service/**
        url: http://192.168.10.9:8889
        stripPrefix: false
        sensitiveHeaders:
        
    ams-service:
        path: /ams-service/**
        url: http://192.168.10.9:8508
        stripPrefix: false
        sensitiveHeaders:
        
    iam-service:
        path: /iam-service/**
        url: http://192.168.10.9:8507
        stripPrefix: false
        sensitiveHeaders:
        
    notification-service:
        path: /notification-service/**
        url: http://192.168.10.9:8509
        stripPrefix: false
        sensitiveHeaders:

server:
  port: 4000

