version: '3.1'

services:

  mongo:
    image: mongo-pcs:latest
    restart: always
    volumes:
      - './data/mongodb:/data/db'
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Smac123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8088:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Smac123
      ME_CONFIG_MONGODB_URL: mongodb://root:Smac123@mongo:27017/