logging:
  level:
    org:
      springframework:
        security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.1.9:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://127.0.0.1:5000/uaa/users/current

spring:
  main:
    allow-circular-references: true
  rabbitmq:
    host: 127.0.0.1
    

feign:
  hystrix:
    enabled: true
    
camunda:
  bpm:
    admin-user:
      password: noodles
      id: noodles
    metrics:
      db-reporter-activate: 'false'
    database:
      schema-update: 'true'
      
minio:
  secretKey: minio-root-password
  endpoint: http://192.168.1.9:9900
  accessKey: minio-root-user
  domain: http://192.168.1.9:9900
  
