logging:
  level:
    org:
      springframework:
        security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.10.9:8761/eureka/

spring:
  main:
    allow-circular-references: true
    

feign:
  hystrix:
    enabled: true
    
camunda:
  bpm:
    admin-user:
      password: noodles
      id: noodles
    metrics:
      db-reporter-activate: 'false'
    database:
      schema-update: 'true'
      
minio:
  secretKey: 123456789
  endpoint: http://192.168.10.9:9990
  accessKey: 123456789
  domain: http://192.168.10.9:9990
  
