logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${URL_REGISTRY_SERVICE}/eureka/

security:
  oauth2:
    resource:
      user-info-uri: ${URL_AUTH_SERVICE}/uaa/users/current

spring:
  rabbitmq:
    host: rabbitmq