spring:
  data:
    mongodb:
      host: ${DB_AUTH_HOST}
      username: root
      password: ${MONGODB_PASSWORD}
      database: admin
      port: 27019

server:
  servlet:
    context-path: /uaa
  port: 5000
