hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    keycloak-service:
        path: /auth/**
        url: http://192.168.10.9:8899
        stripPrefix: false
        sensitiveHeaders:
        
    user-service:
        path: /user-service/**
        url: http://192.168.10.9:8503
        stripPrefix: false
        sensitiveHeaders:

server:
  port: 4000
